### ISSUE TITLE
Feature: User can see existing messages

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see existing messages. Mostly a lot of starter groundwork for setting up the database, the server, and the first react components. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

At this point, the website will be a single page that will load whatever list of messages that is stored under the hardcoded server 'default' in the room 'general'. No continuous updates, just a single render.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/12964172/171045426-121d04f5-2345-4dc4-90b4-441191c5ddeb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create `schema.sql` to store the design for where user and message data will be stored.
- [x] Fill in `data.sql` to pre-populate dummy message data in order to load clientside later.

### ☁️ Server

- [x] Make sure webpack, babel, and other build tools are all happy. 
- [x] Create `server/index.js` to have a functioning API
  - [x] have the api respond to get requests to /api/messages/ 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to hold a list of messages
- [x] Create a message group component with a timestamp
- [x] **On Load** clients should see a list of previous messages.
  - [x] The component should use the fetch API to grab messages from the server to load them. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
