### ISSUE TITLE
Feature: User can authenticate

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can log in and out. Updating existing functionality to pay some attention to user-state.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Have a sign up / sign in landing screen before seeing any content.
When user submits a sign-up form, the API hits /sign-up, then /sign-in
When user submits a sign-in form, the API calls /sign-in
Have some "userID" stored somewhere the app can access.
Make users unable to delete messages written by others.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/12964172/171286576-8faea834-ca64-4280-8744-07a8b6982412.png)
![image](https://user-images.githubusercontent.com/12964172/171286629-ab148436-5e36-4596-9cfb-b8776d5ff13c.png)
![image](https://user-images.githubusercontent.com/12964172/171287255-e27986a7-6379-4ef0-866e-5144b4290a10.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to receive calls to '/api/sign-up'
- [x] Update `server/index.js` to receive calls to '/api/sign-in'
- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client
- [x] various things about the database that happen naturally when testing endpoints

### ⚡ Client

- [x] create components for LogIn screen.
- [x] redirect users without log-in info to the auth screen.
- [x] create a signup and signin modal.
- [x] Tie form submits to API calls
- [x] create component for the "currently connected / logout button"
- [x] tie the logout button to API call
- [ ] Update <Message> component to only show <DeleteConfirmModal> if user matches the post uid

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
