### ISSUE TITLE
Feature: User can see other users typing live

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see other people type live

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user types, it will be sending out live updates to others.

Seems a lot trickier to implement this time around now that React State is in between me and the DOM now.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/12964172/171701542-f9a75f9d-89f9-4692-83fd-b8bf473331c0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] make new socket events to "open" "close" "publish" "update" new live messages
- [x] make sure order of messages is retained

### ⚡ Client

- [x] listen to new socket events
- [x] update the messages object to reflect updates
- [x] make live typed messages greyed out
- [x] make new messages fade in visually

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
