### ISSUE TITLE
Feature: User can add messages

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can use a text input at the bottom of the page to make post-requests to the server API, also known as "sending messages".

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The same as before. I do not plan on having the server update on message send-events until I have web sockets wired up, so if users want to see the messages they have added, they would need to refresh. Just have a chatroom that automatically refreshes every 2 seconds? Big brains solution.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/12964172/171047298-409004ec-7237-4cc7-9318-72a1a4550e19.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to take in post requests to /api/messages/ that writes to the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the chat-bar.
- [x] Update component to vaguely look like the wireframe.
- [x] On submit, it should send a post request to the API that will update the database.

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
