### ISSUE TITLE
Feature: User can see a list of other rooms

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
New sidebar that has a list of other rooms in the server. No functional interactivity.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The app should function the exact same, but now it will have a cute little UI component keeping it company.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/12964172/171750254-f4ffa425-b043-446e-9225-7489d78db72c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a /api/rooms/:serverID endpoint that returns a list of rooms
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to host a list of rooms
- [x] Make the component look good
- [x] Give it a cute little hover effect
- [x] On load somewhere, call the API, and use the result to populate rooms in state somewhere

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
