### ISSUE TITLE
Feature: User can switch between servers

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#25]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to create and join different Servers with their own groups of rooms. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the server name on the very topleft will trigger a modal that allows them to attempt to join a different servername, and if it's unique it will also move to create the server.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to have a few built in servers / rooms for easier testing.

### ☁️ Server

- [x] Update `server/index.js` to have an API endpoint to POST new servers.
- [x] Update `server/index.js` to have an API endpoint to GET a server list.
- [x] Update `server/index.js`'s POST endpoint to also POST to make a new room

### ⚡ Client

- [x] Create a component to act as the UI to switch between servers.
- [x] Update the component to send POST requests to create a new server if it's not selecting an existing one
- [x] Have the component also change some internal state "server-id" object, and the hash value.
- [x] Make sure hash routing is consistent, can refresh within pages and keep server information
- [x] Update change server modal to refresh serverlist on modal open

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
