### ISSUE TITLE
Feature: User can edit their previous messages

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can edit the messages that they have previously sent.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can click on the pencil that's revealed on hover for the message divs, which will restyle the input component, change it's "on submit" action, and prepopulate it with the content of the selected message.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/12964172/171961401-51b8d361-e866-42d3-ac30-0b719b0c74eb.png)
![image](https://user-images.githubusercontent.com/12964172/171961413-85f54604-c1ae-42e8-a714-ff1878e797de.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to add a "has been edited" marker to a message

### ☁️ Server

- [x] Update `server/index.js` to receive UPDATE calls to edit a message, which changes the "content" of the messages table and also edits the database field "edited" to true.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update Messages Component to display a small mark if previously edited.
- [x] Create a hook in the message component for "editing mode open" or not
when you edit while an edit is already open, it should close the current edit mode and then open a new one.

- [x] Have clicking on the pencil icon switch the hook state
- [x] Create a new "EditMessageInput" component that will render if a certain message has the state "isEditing"
- [x] Have the edit icon switch from displaying a message, to displaying the "EditMessageInput" component
- [x] Create the escape to cancel, enter to save reminder / links down below the input
- [ ] actually tie keydowns to functionality. enter should be built in with the form submit action, not entirely sure about pulling off the escape key, is onBlur a react thing?
- [ ] 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
