### ISSUE TITLE
Feature: User can delete their messages

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User click trash icon, confirms modal, and the DOM / database deletes it. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the trashcan icon will open up a modal that will confirm the deletion of a message, which will send a fetch API to delete the selected message.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/12964172/171233331-a0a57d70-07f8-44db-8e26-ce6189ab46f6.png)

![image](https://user-images.githubusercontent.com/12964172/171232957-2b56f445-f018-4df2-abe2-39d16f0c06e7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to listen for a delete endpoint
- [x] Test that it functions as expected with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a confirmation modal when clicking the delete button
- [x] Pretty up the modal to more closely reflect the wire-frame
- [x] On confirm, have the modal send a DELETE request to the API

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
