### ISSUE TITLE
Feature: User can get live message updates

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The page doesn't have to refresh to load in new messages.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Should basically work the same, but more of an actual application.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Get a WS connection between the client and the server up and running
- [x] receive "message send" events from the client
- [x] send "message received" events to all connected clients
- [x] listen for and echo "on delete" events

### ⚡ Client

- [x] add in some WS implementation in app.jsx
- [x] update "on message send" to also send a "message send" event to the server
- [x] update the "messages" state object on receiving messages
- [x] create a "on delete" event so that deleted messages are broadcasted / removed.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
