### ISSUE TITLE
Feature: User can switch between rooms

### ISSUE THREAD

**Issue by luiderek** [luiderek/concord#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can click on the rooms in the sidebar, and access different threads. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
It should work as expected. Click stuff, see different messages, broadcast to different room.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

next to no visual changes, mostly functionality

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database
- [ ] TBD

### ☁️ Server
- [ ] update the read-message API to take both server AND room
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [x] clicking a room on the list changes the URL hash value.
- [ ] clicking a room on the list changes its visual state
- [x] on hash change, update the room-id state
- [x] based on different room-id states, send messages to different rooms
- [x] only load messages from the relevant room-ids
- [x] when you load in from sign-in, the hash should be the first room-id of the room's object.
- [x] when you refresh the page from a hash, the roomID state should not be null
- [ ]
